name: KeepIndividualSpigot
version: '1.0'
main: com.callmeperky.keepindividualspigot.KeepIndividualSpigot
api-version: '1.20'
commands:
  KI:
    description: Keep individual
    usage: /<command>
    aliases: [keepindividual]